### ISSUE TITLE
Energy, etc. Tips + Needs

### ISSUE THREAD

**Issue by bkmi** [machism0/non-bonded-periodic#15]
be able to switch energy from coulomb versus lenard jones energy calc

Don't use a quad deep look in k space. Build a grid of k vectors ahead of time and apply it. In addition, use symmetry to reduce the problem to only real space k vectors

And a more obtuse suggestion:
Take the equations from long range ewald, substitute structure factors, use Euler or symmetry... This process will yield coupled interactions between two particles (but still manage to avoid incorporating any images.) this notion of energy contributions from pairs of particles can be used for the forces. (Another small hint, it involves the complex square of the structure factor)

**Comment by zenpi-me** [comment]
![force](https://user-images.githubusercontent.com/23185551/35588573-60b1bd62-0601-11e8-9714-e81cd7ded4af.JPG)

First of all: Thank you for your suggestions and your time.

I am thinking that I can just take the energies and calc the negative gradient from them. I already did this and if you like you can see. Because I am not sure, if I can just do it like that. I actually just did "force = -np.diff(energy)/distance"...

The k vector grid is also implemented and I use symmetry. There is nothing imaginary anymore.

I don't understand your last suggestion :/ what images are you talking about?

**Comment by TracyMcBean** [comment]
I think the problem with the symmetry of the k vectors has been solved. In case this is not the case I would suggest opening a new issue which is up to date.
